### ISSUE TITLE
function.ssh2-disconnect [php5-en]

### ISSUE THREAD

**Issue by HassanKrayem** [zendtech/php-legacy-docs#9]
When every I call ssh disconnect request returns 502 gateway error

Tested on Ubuntu, Ngnix, PHP v7.4.3

**Comment by afilina** [comment]
Hello. This is not the appropriate place to post this kind of issue. Here, we only manage the legacy documentation that was discontinued on the official PHP website.

For bugs in PHP: https://bugs.php.net/
For support from the community: https://phpc.chat/
